// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnJZ6dpoeGDNWg2jrisULYUDxN2ZDARM',
    appId: '1:422456503202:web:63dd15c9f8ced578ce20fb',
    messagingSenderId: '422456503202',
    projectId: 'anedya-sparkle',
    authDomain: 'anedya-sparkle.firebaseapp.com',
    storageBucket: 'anedya-sparkle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIzSYFREA6brUUjCB_5YLXpz0oSMr5vM',
    appId: '1:422456503202:android:7ca65380526a7c9ace20fb',
    messagingSenderId: '422456503202',
    projectId: 'anedya-sparkle',
    storageBucket: 'anedya-sparkle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEsWkU3XquUlDVOaZi3oA4L5OjCb-teC4',
    appId: '1:422456503202:ios:75def2338ea03130ce20fb',
    messagingSenderId: '422456503202',
    projectId: 'anedya-sparkle',
    storageBucket: 'anedya-sparkle.firebasestorage.app',
    iosBundleId: 'com.example.sparkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEsWkU3XquUlDVOaZi3oA4L5OjCb-teC4',
    appId: '1:422456503202:ios:75def2338ea03130ce20fb',
    messagingSenderId: '422456503202',
    projectId: 'anedya-sparkle',
    storageBucket: 'anedya-sparkle.firebasestorage.app',
    iosBundleId: 'com.example.sparkle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnJZ6dpoeGDNWg2jrisULYUDxN2ZDARM',
    appId: '1:422456503202:web:911ea12ff2f532f1ce20fb',
    messagingSenderId: '422456503202',
    projectId: 'anedya-sparkle',
    authDomain: 'anedya-sparkle.firebaseapp.com',
    storageBucket: 'anedya-sparkle.firebasestorage.app',
  );
}
